config/routes.rb
Docbic9::Application.routes.draw do
  

  match 'pacients/verifica_cnp', :controller => "pacients", :action => "verifica_cnp"
  resources :vizita do 
    resource :paraclinice
    resource :mi
    resource :clinic
    resource :anamneza
    resource :sga
  end
  resources :pacients do 
    member do
      get "screening"
      get "verifica_cnp"
    end
    collection do
      get "consent"
    end
    resources :vizita do
      resources :paraclinices
    end
    resources :sf36s
    resources :paraclinices
    resources :medicamentes
    resources :pacient_iesits
  end

   root :to => 'pacients#index'

end

app/models/anamneza.rb
class Anamneza < ActiveRecord::Base
  belongs_to :vizitum
end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
  belongs_to :vizitum
  validates_presence_of :inaltime, :if => :screening?
  validates_presence_of :greutate, :if => :screening?
  def screening?
    self.vizitum.tip == "screening"
  end
end

app/models/medicamente.rb
class Medicamente < ActiveRecord::Base
  belongs_to :vizitum
end

app/models/mi.rb
class Mi < ActiveRecord::Base
  belongs_to :vizitum
end

app/models/pacient.rb
#encoding: utf-8
class Pacient < ActiveRecord::Base
  self.per_page = 5
  CENTRE = ["Paulescu", "Davila"]
  has_many :vizita
  accepts_nested_attributes_for :vizita
  validates :semnat_icf, :acceptance => true #, :message => "E musai ca pacientul să semneze inform consentul"
  validates :cnp, :length => { :is =>13, :wrong_length => "CNP are 13 cifre" }, :numericality => { :only_integer =>true}
  validates_format_of :telefon1, :with => /\d{10}/, :message => "Un număr de telefon în România are 10 cifre"
  validates_format_of :telefon2, :with => /\d{10}/, :message => "Un număr de telefon în România are 10 cifre"
  def self.search(search, page) #tot nu merge
    if search
      paginate :per_page => 5, :page => page,
        :conditions => ['nume like ?', "%#{search}%"], :order => 'nume'
      #find(:all, :conditions => ['nume LIKE ?', "%#{search}"])
    else
      find(:all)
    end
  end
end

app/models/pacient_iesit.rb
class PacientIesit < ActiveRecord::Base
  belongs_to :pacient
end

app/models/paraclinice.rb
class Paraclinice < ActiveRecord::Base
  belongs_to :vizita
  validates_presence_of :hba1c, :if => :screening?
  validates_presence_of :hco3, :if => :screening?
  def screening?
    self.vizitum.tip == "screening"
  end
end

app/models/sf36.rb
class Sf36 < ActiveRecord::Base
  belongs_to :pacient
end

app/models/sga.rb
class Sga < ActiveRecord::Base
end

app/models/vizitum.rb
class Vizitum < ActiveRecord::Base
  #nu imi trebuie validari pt screening 
  belongs_to :pacient
  has_one :paraclinice
  has_one :medicamente
  has_one :mi
  has_one :anamneza
  has_one :clinic
  has_one :sga
  accepts_nested_attributes_for :paraclinice
  accepts_nested_attributes_for :medicamente
  accepts_nested_attributes_for :mi
  accepts_nested_attributes_for :sga
  accepts_nested_attributes_for :clinic
  accepts_nested_attributes_for :anamneza
  before_update :prelucreaza_nutritia
  #validates_presence_of :data, :if => :screening?
  def screening?
    self.tip == "screening"
  end
  def criterii_includere
    if self.tip == "screening"
      if self.paraclinice.hba1c > 8
        errors.add_to_base("Pacient dezechilibrat")
      end
    end
  end
  private
  def verifica_criterii
    if self.tip == "screening" #conditiile nu sunt bune
      puts 'glicozilata e'
      puts self.paraclinice.hba1c
      #if self.paraclinice.hba1c > 8 or calculeaza_epi > 30 or self.paraclinice.hco3 < 20
        #self.pacient.inclus=false
      #end
    end
  end
  def calculeaza_epi
    cnp = self.pacient.cnp
    an_nastere = '19'+ cnp[1,2]
    varsta = Date.today.year.to_int - an_nastere
    if cnp[0] == 1
      k = 0.9
      alfa = -0.4111
      coeficient = 1
    elsif cnp[0] == 2
      k = 0.7
      alfa = -0.329
      coeficient = 1.018
    end
    raport = self.paraclinice.creatinina/k
    primu = [raport, 1].min**-0.411
    doilea = [raport, 1].max ** -1.209
    treilea = 0.993**89
    puts 'epi zice'
    puts 141*primu*doilea*treilea*coeficient
    141*primu*doilea*treilea*coeficient
  end
  def calculeaza_bmi_categorie(inaltime, greutate)
    puts 'G=', greutate, 'I=', inaltime
    bmi = greutate/(inaltime **2)
    case bmi
    when bmi > 20
      bmi_categorie = 0
    when 18 .. 20
      bmi_categorie = 1
    when 16 .. 18
      bmi_categorie =2
    when bmi <16
      bmi_categorie =3
    end
    puts bmi_categorie
    bmi_categorie
  end
  def prelucreaza_nutritia
    puts 'salut din callback'
    if self.tip == "screening"
      puts 'data vizitei e', self.data
      puts 'data anamnezei e', self.anamneza.data
      puts 'glicozilata e', self.paraclinice.hba1c #merge si pot calcula lucruri
    end
  end
end

class PrelucreazaNutritia
  def before_save(record)
    record.tip = "screening"
  end
  #alias_method :before_save
end

app/controllers/mis_controller.rb
class MisController < InheritedResources::Base
  belongs_to :vizita
end

app/controllers/sf36s_controller.rb
class Sf36sController < InheritedResources::Base
end

app/controllers/sgas_controller.rb
class SgasController < InheritedResources::Base
end

app/helpers/anamnezas_helper.rb
module AnamnezasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/helpers/medicamentes_helper.rb
module MedicamentesHelper
end

app/helpers/mis_helper.rb
module MisHelper
end

app/helpers/pacients_helper.rb
module PacientsHelper
end

app/helpers/paraclinices_helper.rb
module ParaclinicesHelper
end

app/helpers/sf36s_helper.rb
module Sf36sHelper
end

app/helpers/sgas_helper.rb
module SgasHelper
end

app/helpers/vizita_helper.rb
module VizitaHelper
end

app/views/mis/_form.html.erb
<%= form_for(@mi) do |f| %>
  <% if @mi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mi.errors.count, "error") %> prohibited this mi from being saved:</h2>

      <ul>
      <% @mi.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :greutate %><br />
    <%= f.number_field :greutate %>
  </div>
  <div class="field">
    <%= f.label :aport %><br />
    <%= f.number_field :aport %>
  </div>
  <div class="field">
    <%= f.label :simptome_gi %><br />
    <%= f.number_field :simptome_gi %>
  </div>
  <div class="field">
    <%= f.label :capacitate_functionala %><br />
    <%= f.number_field :capacitate_functionala %>
  </div>
  <div class="field">
    <%= f.label :co-morbiditate %><br />
    <%= f.number_field :co-morbiditate %>
  </div>
  <div class="field">
    <%= f.label :grasime %><br />
    <%= f.number_field :grasime %>
  </div>
  <div class="field">
    <%= f.label :muschi %><br />
    <%= f.number_field :muschi %>
  </div>
  <div class="field">
    <%= f.label :bmi %><br />
    <%= f.number_field :bmi %>
  </div>
  <div class="field">
    <%= f.label :albumina %><br />
    <%= f.number_field :albumina %>
  </div>
  <div class="field">
    <%= f.label :tibc %><br />
    <%= f.number_field :tibc %>
  </div>
  <div class="field">
    <%= f.label :vizita %><br />
    <%= f.text_field :vizita %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mis/edit.html.erb
<h1>Editing mi</h1>

<%= render 'form' %>

<%= link_to 'Show', @mi %> |
<%= link_to 'Back', mis_path %>

app/views/mis/index.html.erb
<h1>Listing mis</h1>

<table>
  <tr>
    <th>Greutate</th>
    <th>Aport</th>
    <th>Simptome gi</th>
    <th>Capacitate functionala</th>
    <th>Co-morbiditate</th>
    <th>Grasime</th>
    <th>Muschi</th>
    <th>Bmi</th>
    <th>Albumina</th>
    <th>Tibc</th>
    <th>Vizita</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mis.each do |mi| %>
  <tr>
    <td><%= mi.greutate %></td>
    <td><%= mi.aport %></td>
    <td><%= mi.simptome_gi %></td>
    <td><%= mi.capacitate_functionala %></td>
    <td><%= mi.co-morbiditate %></td>
    <td><%= mi.grasime %></td>
    <td><%= mi.muschi %></td>
    <td><%= mi.bmi %></td>
    <td><%= mi.albumina %></td>
    <td><%= mi.tibc %></td>
    <td><%= mi.vizita %></td>
    <td><%= link_to 'Show', mi %></td>
    <td><%= link_to 'Edit', edit_mi_path(mi) %></td>
    <td><%= link_to 'Destroy', mi, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mi', new_mi_path %>

app/views/mis/new.html.erb
<h1>New mi</h1>

<%= render 'form' %>

<%= link_to 'Back', mis_path %>

app/views/mis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Greutate:</b>
  <%= @mi.greutate %>
</p>

<p>
  <b>Aport:</b>
  <%= @mi.aport %>
</p>

<p>
  <b>Simptome gi:</b>
  <%= @mi.simptome_gi %>
</p>

<p>
  <b>Capacitate functionala:</b>
  <%= @mi.capacitate_functionala %>
</p>

<p>
  <b>Co-morbiditate:</b>
  <%= @mi.co-morbiditate %>
</p>

<p>
  <b>Grasime:</b>
  <%= @mi.grasime %>
</p>

<p>
  <b>Muschi:</b>
  <%= @mi.muschi %>
</p>

<p>
  <b>Bmi:</b>
  <%= @mi.bmi %>
</p>

<p>
  <b>Albumina:</b>
  <%= @mi.albumina %>
</p>

<p>
  <b>Tibc:</b>
  <%= @mi.tibc %>
</p>

<p>
  <b>Vizita:</b>
  <%= @mi.vizita %>
</p>


<%= link_to 'Edit', edit_mi_path(@mi) %> |
<%= link_to 'Back', mis_path %>

app/views/sf36s/_form.html.erb
<%= form_for(@sf36) do |f| %>
  <% if @sf36.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sf36.errors.count, "error") %> prohibited this sf36 from being saved:</h2>

      <ul>
      <% @sf36.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pacient %><br />
    <%= f.text_field :pacient %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :sanatatea %><br />
    <%= f.number_field :sanatatea %>
  </div>
  <div class="field">
    <%= f.label :sanatatea_comparativ %><br />
    <%= f.number_field :sanatatea_comparativ %>
  </div>
  <div class="field">
    <%= f.label :activitati_obositoare %><br />
    <%= f.number_field :activitati_obositoare %>
  </div>
  <div class="field">
    <%= f.label :activitati_moderate %><br />
    <%= f.number_field :activitati_moderate %>
  </div>
  <div class="field">
    <%= f.label :ridicat %><br />
    <%= f.number_field :ridicat %>
  </div>
  <div class="field">
    <%= f.label :urcat_etaje %><br />
    <%= f.number_field :urcat_etaje %>
  </div>
  <div class="field">
    <%= f.label :urcat_etaj %><br />
    <%= f.number_field :urcat_etaj %>
  </div>
  <div class="field">
    <%= f.label :aplecat %><br />
    <%= f.number_field :aplecat %>
  </div>
  <div class="field">
    <%= f.label :km1 %><br />
    <%= f.number_field :km1 %>
  </div>
  <div class="field">
    <%= f.label :sute_metri %><br />
    <%= f.number_field :sute_metri %>
  </div>
  <div class="field">
    <%= f.label :o_suta_metri %><br />
    <%= f.number_field :o_suta_metri %>
  </div>
  <div class="field">
    <%= f.label :imbaiere %><br />
    <%= f.number_field :imbaiere %>
  </div>
  <div class="field">
    <%= f.label :perioada_timp %><br />
    <%= f.check_box :perioada_timp %>
  </div>
  <div class="field">
    <%= f.label :mai_putine %><br />
    <%= f.check_box :mai_putine %>
  </div>
  <div class="field">
    <%= f.label :limitat %><br />
    <%= f.check_box :limitat %>
  </div>
  <div class="field">
    <%= f.label :dificultati %><br />
    <%= f.check_box :dificultati %>
  </div>
  <div class="field">
    <%= f.label :perioada_emotionale %><br />
    <%= f.check_box :perioada_emotionale %>
  </div>
  <div class="field">
    <%= f.label :mai_putine_emotionale %><br />
    <%= f.check_box :mai_putine_emotionale %>
  </div>
  <div class="field">
    <%= f.label :grija %><br />
    <%= f.check_box :grija %>
  </div>
  <div class="field">
    <%= f.label :familie %><br />
    <%= f.number_field :familie %>
  </div>
  <div class="field">
    <%= f.label :dureri %><br />
    <%= f.number_field :dureri %>
  </div>
  <div class="field">
    <%= f.label :durerea %><br />
    <%= f.number_field :durerea %>
  </div>
  <div class="field">
    <%= f.label :plin_viata %><br />
    <%= f.number_field :plin_viata %>
  </div>
  <div class="field">
    <%= f.label :nervos %><br />
    <%= f.number_field :nervos %>
  </div>
  <div class="field">
    <%= f.label :deprimat %><br />
    <%= f.number_field :deprimat %>
  </div>
  <div class="field">
    <%= f.label :calm %><br />
    <%= f.number_field :calm %>
  </div>
  <div class="field">
    <%= f.label :energie %><br />
    <%= f.number_field :energie %>
  </div>
  <div class="field">
    <%= f.label :descurajat %><br />
    <%= f.number_field :descurajat %>
  </div>
  <div class="field">
    <%= f.label :extenuat %><br />
    <%= f.number_field :extenuat %>
  </div>
  <div class="field">
    <%= f.label :fericit %><br />
    <%= f.number_field :fericit %>
  </div>
  <div class="field">
    <%= f.label :obosit %><br />
    <%= f.number_field :obosit %>
  </div>
  <div class="field">
    <%= f.label :vizite %><br />
    <%= f.number_field :vizite %>
  </div>
  <div class="field">
    <%= f.label :imbolnavesc %><br />
    <%= f.number_field :imbolnavesc %>
  </div>
  <div class="field">
    <%= f.label :la_fel %><br />
    <%= f.number_field :la_fel %>
  </div>
  <div class="field">
    <%= f.label :inrautateasca %><br />
    <%= f.number_field :inrautateasca %>
  </div>
  <div class="field">
    <%= f.label :sanatate_excelenta %><br />
    <%= f.number_field :sanatate_excelenta %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sf36s/edit.html.erb
<h1>Editing sf36</h1>

<%= render 'form' %>

<%= link_to 'Show', @sf36 %> |
<%= link_to 'Back', sf36s_path %>

app/views/sf36s/index.html.erb
<h1>Listing sf36s</h1>

<table>
  <tr>
    <th>Pacient</th>
    <th>Data</th>
    <th>Sanatatea</th>
    <th>Sanatatea comparativ</th>
    <th>Activitati obositoare</th>
    <th>Activitati moderate</th>
    <th>Ridicat</th>
    <th>Urcat etaje</th>
    <th>Urcat etaj</th>
    <th>Aplecat</th>
    <th>Km1</th>
    <th>Sute metri</th>
    <th>O suta metri</th>
    <th>Imbaiere</th>
    <th>Perioada timp</th>
    <th>Mai putine</th>
    <th>Limitat</th>
    <th>Dificultati</th>
    <th>Perioada emotionale</th>
    <th>Mai putine emotionale</th>
    <th>Grija</th>
    <th>Familie</th>
    <th>Dureri</th>
    <th>Durerea</th>
    <th>Plin viata</th>
    <th>Nervos</th>
    <th>Deprimat</th>
    <th>Calm</th>
    <th>Energie</th>
    <th>Descurajat</th>
    <th>Extenuat</th>
    <th>Fericit</th>
    <th>Obosit</th>
    <th>Vizite</th>
    <th>Imbolnavesc</th>
    <th>La fel</th>
    <th>Inrautateasca</th>
    <th>Sanatate excelenta</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sf36s.each do |sf36| %>
  <tr>
    <td><%= sf36.pacient %></td>
    <td><%= sf36.data %></td>
    <td><%= sf36.sanatatea %></td>
    <td><%= sf36.sanatatea_comparativ %></td>
    <td><%= sf36.activitati_obositoare %></td>
    <td><%= sf36.activitati_moderate %></td>
    <td><%= sf36.ridicat %></td>
    <td><%= sf36.urcat_etaje %></td>
    <td><%= sf36.urcat_etaj %></td>
    <td><%= sf36.aplecat %></td>
    <td><%= sf36.km1 %></td>
    <td><%= sf36.sute_metri %></td>
    <td><%= sf36.o_suta_metri %></td>
    <td><%= sf36.imbaiere %></td>
    <td><%= sf36.perioada_timp %></td>
    <td><%= sf36.mai_putine %></td>
    <td><%= sf36.limitat %></td>
    <td><%= sf36.dificultati %></td>
    <td><%= sf36.perioada_emotionale %></td>
    <td><%= sf36.mai_putine_emotionale %></td>
    <td><%= sf36.grija %></td>
    <td><%= sf36.familie %></td>
    <td><%= sf36.dureri %></td>
    <td><%= sf36.durerea %></td>
    <td><%= sf36.plin_viata %></td>
    <td><%= sf36.nervos %></td>
    <td><%= sf36.deprimat %></td>
    <td><%= sf36.calm %></td>
    <td><%= sf36.energie %></td>
    <td><%= sf36.descurajat %></td>
    <td><%= sf36.extenuat %></td>
    <td><%= sf36.fericit %></td>
    <td><%= sf36.obosit %></td>
    <td><%= sf36.vizite %></td>
    <td><%= sf36.imbolnavesc %></td>
    <td><%= sf36.la_fel %></td>
    <td><%= sf36.inrautateasca %></td>
    <td><%= sf36.sanatate_excelenta %></td>
    <td><%= link_to 'Show', sf36 %></td>
    <td><%= link_to 'Edit', edit_sf36_path(sf36) %></td>
    <td><%= link_to 'Destroy', sf36, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sf36', new_sf36_path %>

app/views/sf36s/new.html.erb
<h1>New sf36</h1>

<%= render 'form' %>

<%= link_to 'Back', sf36s_path %>

app/views/sf36s/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pacient:</b>
  <%= @sf36.pacient %>
</p>

<p>
  <b>Data:</b>
  <%= @sf36.data %>
</p>

<p>
  <b>Sanatatea:</b>
  <%= @sf36.sanatatea %>
</p>

<p>
  <b>Sanatatea comparativ:</b>
  <%= @sf36.sanatatea_comparativ %>
</p>

<p>
  <b>Activitati obositoare:</b>
  <%= @sf36.activitati_obositoare %>
</p>

<p>
  <b>Activitati moderate:</b>
  <%= @sf36.activitati_moderate %>
</p>

<p>
  <b>Ridicat:</b>
  <%= @sf36.ridicat %>
</p>

<p>
  <b>Urcat etaje:</b>
  <%= @sf36.urcat_etaje %>
</p>

<p>
  <b>Urcat etaj:</b>
  <%= @sf36.urcat_etaj %>
</p>

<p>
  <b>Aplecat:</b>
  <%= @sf36.aplecat %>
</p>

<p>
  <b>Km1:</b>
  <%= @sf36.km1 %>
</p>

<p>
  <b>Sute metri:</b>
  <%= @sf36.sute_metri %>
</p>

<p>
  <b>O suta metri:</b>
  <%= @sf36.o_suta_metri %>
</p>

<p>
  <b>Imbaiere:</b>
  <%= @sf36.imbaiere %>
</p>

<p>
  <b>Perioada timp:</b>
  <%= @sf36.perioada_timp %>
</p>

<p>
  <b>Mai putine:</b>
  <%= @sf36.mai_putine %>
</p>

<p>
  <b>Limitat:</b>
  <%= @sf36.limitat %>
</p>

<p>
  <b>Dificultati:</b>
  <%= @sf36.dificultati %>
</p>

<p>
  <b>Perioada emotionale:</b>
  <%= @sf36.perioada_emotionale %>
</p>

<p>
  <b>Mai putine emotionale:</b>
  <%= @sf36.mai_putine_emotionale %>
</p>

<p>
  <b>Grija:</b>
  <%= @sf36.grija %>
</p>

<p>
  <b>Familie:</b>
  <%= @sf36.familie %>
</p>

<p>
  <b>Dureri:</b>
  <%= @sf36.dureri %>
</p>

<p>
  <b>Durerea:</b>
  <%= @sf36.durerea %>
</p>

<p>
  <b>Plin viata:</b>
  <%= @sf36.plin_viata %>
</p>

<p>
  <b>Nervos:</b>
  <%= @sf36.nervos %>
</p>

<p>
  <b>Deprimat:</b>
  <%= @sf36.deprimat %>
</p>

<p>
  <b>Calm:</b>
  <%= @sf36.calm %>
</p>

<p>
  <b>Energie:</b>
  <%= @sf36.energie %>
</p>

<p>
  <b>Descurajat:</b>
  <%= @sf36.descurajat %>
</p>

<p>
  <b>Extenuat:</b>
  <%= @sf36.extenuat %>
</p>

<p>
  <b>Fericit:</b>
  <%= @sf36.fericit %>
</p>

<p>
  <b>Obosit:</b>
  <%= @sf36.obosit %>
</p>

<p>
  <b>Vizite:</b>
  <%= @sf36.vizite %>
</p>

<p>
  <b>Imbolnavesc:</b>
  <%= @sf36.imbolnavesc %>
</p>

<p>
  <b>La fel:</b>
  <%= @sf36.la_fel %>
</p>

<p>
  <b>Inrautateasca:</b>
  <%= @sf36.inrautateasca %>
</p>

<p>
  <b>Sanatate excelenta:</b>
  <%= @sf36.sanatate_excelenta %>
</p>


<%= link_to 'Edit', edit_sf36_path(@sf36) %> |
<%= link_to 'Back', sf36s_path %>

app/views/sgas/_form.html.erb
<%= form_for(@sga) do |f| %>
  <% if @sga.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sga.errors.count, "error") %> prohibited this sga from being saved:</h2>

      <ul>
      <% @sga.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pacient %><br />
    <%= f.text_field :pacient %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :modificari_greutate %><br />
    <%= f.number_field :modificari_greutate %>
  </div>
  <div class="field">
    <%= f.label :modificari_aport_alimentar %><br />
    <%= f.number_field :modificari_aport_alimentar %>
  </div>
  <div class="field">
    <%= f.label :simptome_gi %><br />
    <%= f.number_field :simptome_gi %>
  </div>
  <div class="field">
    <%= f.label :capacitate_functionala %><br />
    <%= f.number_field :capacitate_functionala %>
  </div>
  <div class="field">
    <%= f.label :comorbiditatea %><br />
    <%= f.number_field :comorbiditatea %>
  </div>
  <div class="field">
    <%= f.label :grasime %><br />
    <%= f.number_field :grasime %>
  </div>
  <div class="field">
    <%= f.label :amiotrofie %><br />
    <%= f.number_field :amiotrofie %>
  </div>
  <div class="field">
    <%= f.label :imc %><br />
    <%= f.number_field :imc %>
  </div>
  <div class="field">
    <%= f.label :pcr %><br />
    <%= f.number_field :pcr %>
  </div>
  <div class="field">
    <%= f.label :feritina %><br />
    <%= f.number_field :feritina %>
  </div>
  <div class="field">
    <%= f.label :albumina %><br />
    <%= f.number_field :albumina %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sgas/edit.html.erb
<h1>Editing sga</h1>

<%= render 'form' %>

<%= link_to 'Show', @sga %> |
<%= link_to 'Back', sgas_path %>

app/views/sgas/index.html.erb
<h1>Listing sgas</h1>

<table>
  <tr>
    <th>Pacient</th>
    <th>Data</th>
    <th>Modificari greutate</th>
    <th>Modificari aport alimentar</th>
    <th>Simptome gi</th>
    <th>Capacitate functionala</th>
    <th>Comorbiditatea</th>
    <th>Grasime</th>
    <th>Amiotrofie</th>
    <th>Imc</th>
    <th>Pcr</th>
    <th>Feritina</th>
    <th>Albumina</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sgas.each do |sga| %>
  <tr>
    <td><%= sga.pacient %></td>
    <td><%= sga.data %></td>
    <td><%= sga.modificari_greutate %></td>
    <td><%= sga.modificari_aport_alimentar %></td>
    <td><%= sga.simptome_gi %></td>
    <td><%= sga.capacitate_functionala %></td>
    <td><%= sga.comorbiditatea %></td>
    <td><%= sga.grasime %></td>
    <td><%= sga.amiotrofie %></td>
    <td><%= sga.imc %></td>
    <td><%= sga.pcr %></td>
    <td><%= sga.feritina %></td>
    <td><%= sga.albumina %></td>
    <td><%= link_to 'Show', sga %></td>
    <td><%= link_to 'Edit', edit_sga_path(sga) %></td>
    <td><%= link_to 'Destroy', sga, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sga', new_sga_path %>

app/views/sgas/new.html.erb
<h1>New sga</h1>

<%= render 'form' %>

<%= link_to 'Back', sgas_path %>

app/views/sgas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pacient:</b>
  <%= @sga.pacient %>
</p>

<p>
  <b>Data:</b>
  <%= @sga.data %>
</p>

<p>
  <b>Modificari greutate:</b>
  <%= @sga.modificari_greutate %>
</p>

<p>
  <b>Modificari aport alimentar:</b>
  <%= @sga.modificari_aport_alimentar %>
</p>

<p>
  <b>Simptome gi:</b>
  <%= @sga.simptome_gi %>
</p>

<p>
  <b>Capacitate functionala:</b>
  <%= @sga.capacitate_functionala %>
</p>

<p>
  <b>Comorbiditatea:</b>
  <%= @sga.comorbiditatea %>
</p>

<p>
  <b>Grasime:</b>
  <%= @sga.grasime %>
</p>

<p>
  <b>Amiotrofie:</b>
  <%= @sga.amiotrofie %>
</p>

<p>
  <b>Imc:</b>
  <%= @sga.imc %>
</p>

<p>
  <b>Pcr:</b>
  <%= @sga.pcr %>
</p>

<p>
  <b>Feritina:</b>
  <%= @sga.feritina %>
</p>

<p>
  <b>Albumina:</b>
  <%= @sga.albumina %>
</p>


<%= link_to 'Edit', edit_sga_path(@sga) %> |
<%= link_to 'Back', sgas_path %>