config/routes.rb
Docbic9::Application.routes.draw do
  

  match 'pacients/verifica_cnp', :controller => "pacients", :action => "verifica_cnp"
  resources :vizita do 
    resource :paraclinice
    resource :mi
    resource :clinic
    resource :anamneza
    resource :sga
  end
  resources :pacients do 
    member do
      get "screening"
      get "verifica_cnp"
    end
    collection do
      get "consent"
    end
    resources :vizita do
      resources :paraclinices
    end
    resources :sf36s
    resources :paraclinices
    resources :medicamentes
    resources :pacient_iesits
  end

   root :to => 'pacients#index'

end

app/models/anamneza.rb
class Anamneza < ActiveRecord::Base
  belongs_to :vizitum
end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
  belongs_to :vizitum
  validates_presence_of :inaltime, :if => :screening?
  validates_presence_of :greutate, :if => :screening?
  def screening?
    self.vizitum.tip == "screening"
  end
end

app/models/medicamente.rb
class Medicamente < ActiveRecord::Base
  belongs_to :vizitum
end

app/models/mi.rb
class Mi < ActiveRecord::Base
  belongs_to :vizitum
end

app/models/pacient.rb
#encoding: utf-8
class Pacient < ActiveRecord::Base
  self.per_page = 5
  CENTRE = ["Paulescu", "Davila"]
  has_many :vizita
  accepts_nested_attributes_for :vizita
  validates :semnat_icf, :acceptance => true #, :message => "E musai ca pacientul să semneze inform consentul"
  validates :cnp, :length => { :is =>13, :wrong_length => "CNP are 13 cifre" }, :numericality => { :only_integer =>true}
  validates_format_of :telefon1, :with => /\d{10}/, :message => "Un număr de telefon în România are 10 cifre"
  validates_format_of :telefon2, :with => /\d{10}/, :message => "Un număr de telefon în România are 10 cifre"
  def self.search(search, page) #tot nu merge
    if search
      paginate :per_page => 5, :page => page,
        :conditions => ['nume like ?', "%#{search}%"], :order => 'nume'
      #find(:all, :conditions => ['nume LIKE ?', "%#{search}"])
    else
      find(:all)
    end
  end
end

app/models/pacient_iesit.rb
class PacientIesit < ActiveRecord::Base
  belongs_to :pacient
end

app/models/paraclinice.rb
class Paraclinice < ActiveRecord::Base
  belongs_to :vizita
  validates_presence_of :hba1c, :if => :screening?
  validates_presence_of :hco3, :if => :screening?
  def screening?
    self.vizitum.tip == "screening"
  end
end

app/models/sf36.rb
class Sf36 < ActiveRecord::Base
  belongs_to :pacient
end

app/models/sga.rb
class Sga < ActiveRecord::Base
end

app/models/vizitum.rb
class Vizitum < ActiveRecord::Base
  #nu imi trebuie validari pt screening 
  belongs_to :pacient
  has_one :paraclinice
  has_one :medicamente
  has_one :mi
  has_one :anamneza
  has_one :clinic
  has_one :sga
  accepts_nested_attributes_for :paraclinice
  accepts_nested_attributes_for :medicamente
  accepts_nested_attributes_for :mi
  accepts_nested_attributes_for :sga
  accepts_nested_attributes_for :clinic
  accepts_nested_attributes_for :anamneza
  before_update :prelucreaza_nutritia
  #validates_presence_of :data, :if => :screening?
  def screening?
    self.tip == "screening"
  end
  def criterii_includere
    if self.tip == "screening"
      if self.paraclinice.hba1c > 8
        errors.add_to_base("Pacient dezechilibrat")
      end
    end
  end
  private
  def verifica_criterii
    if self.tip == "screening" #conditiile nu sunt bune
      puts 'glicozilata e'
      puts self.paraclinice.hba1c
      #if self.paraclinice.hba1c > 8 or calculeaza_epi > 30 or self.paraclinice.hco3 < 20
        #self.pacient.inclus=false
      #end
    end
  end
  def calculeaza_epi
    cnp = self.pacient.cnp
    an_nastere = '19'+ cnp[1,2]
    varsta = Date.today.year.to_int - an_nastere
    if cnp[0] == 1
      k = 0.9
      alfa = -0.4111
      coeficient = 1
    elsif cnp[0] == 2
      k = 0.7
      alfa = -0.329
      coeficient = 1.018
    end
    raport = self.paraclinice.creatinina/k
    primu = [raport, 1].min**-0.411
    doilea = [raport, 1].max ** -1.209
    treilea = 0.993**89
    puts 'epi zice'
    puts 141*primu*doilea*treilea*coeficient
    141*primu*doilea*treilea*coeficient
  end
  def calculeaza_bmi_categorie(inaltime, greutate)
    puts 'G=', greutate, 'I=', inaltime
    bmi = greutate/(inaltime **2)
    case bmi
    when bmi > 20
      bmi_categorie = 0
    when 18 .. 20
      bmi_categorie = 1
    when 16 .. 18
      bmi_categorie =2
    when bmi <16
      bmi_categorie =3
    end
    puts bmi_categorie
    bmi_categorie
  end
  def prelucreaza_nutritia
    puts 'salut din callback'
    if self.tip == "screening"
      puts 'data vizitei e', self.data
      puts 'data anamnezei e', self.anamneza.data
      puts 'glicozilata e', self.paraclinice.hba1c #merge si pot calcula lucruri
    end
  end
end

class PrelucreazaNutritia
  def before_save(record)
    record.tip = "screening"
  end
  #alias_method :before_save
end

app/controllers/mis_controller.rb
class MisController < InheritedResources::Base
  belongs_to :vizita
end

app/controllers/pacients_controller.rb
require 'will_paginate/array'
class PacientsController < InheritedResources::Base
  respond_to :html, :js, :json
  respond_to :pdf, :only => :consent
  def verifica_cnp
    @pacient = Pacient.find_by_cnp(params[:pacient][:cnp])
    respond_to do |format|
      format.json { render :json => !@pacient}
    end
  end

  def consent
    respond_to do |format|
      format.pdf do
        send_data Inform.new.to_pdf, :filename => "InformConsent.pdf", :type => "application/pdf",
                                      :page_size => "A4"
      end
    end
  end

  def index
    @pacients = Pacient.paginate(:page => params[:page])
  end

  def create
     @pacient = Pacient.new(params[:pacient])
     respond_to do |format|
       if @pacient.save
         format.html {redirect_to new_pacient_vizitum_path(@pacient, :tip => "screening" )}
       else
         format.html { render :action => "new"}
       end
     end
  end



end

app/controllers/sgas_controller.rb
class SgasController < InheritedResources::Base
end

app/helpers/anamnezas_helper.rb
module AnamnezasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/helpers/medicamentes_helper.rb
module MedicamentesHelper
end

app/helpers/mis_helper.rb
module MisHelper
end

app/helpers/pacients_helper.rb
module PacientsHelper
end

app/helpers/paraclinices_helper.rb
module ParaclinicesHelper
end

app/helpers/sf36s_helper.rb
module Sf36sHelper
end

app/helpers/sgas_helper.rb
module SgasHelper
end

app/helpers/vizita_helper.rb
module VizitaHelper
end

app/views/pacients/_form.html.erb
<%= javascript_include_tag "pacients" %>
<%= stylesheet_link_tag "pacients" %>
<div id="pagina" >
<%= simple_form_for(@pacient) do |f| %>
<h1>Pacient nou </h1>
  <% if @pacient.errors.any? %>
    <div id="error_explanation">
      <h2> Unele date ale pacientului <%= @pacient.nume %> sunt introduse greşit.<br />
      Ai <%= @pacient.errors.count%> erori:  </h2>

      <ul>
      <% @pacient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nume %>
    <%= f.text_field :nume %>
  </div>
  <div class="field">
    <%= f.label :prenume %>
    <%= f.text_field :prenume %>
  </div>
  <div class="field">
    <%= f.label :cnp %>
    <%= f.text_field :cnp %>
  </div>
  <div class="field">
    <%= f.label :telefon1 %>
    <%= f.text_field :telefon1 %>
  </div>
  <div class="field">
    <%= f.label :telefon2 %>
    <%= f.text_field :telefon2 %>
  </div>
  <div class="field">
    <%= f.label :adresa %><br />
    <%= f.text_area :adresa, :rows => 3 %>
  </div>
  <div class="field">
    <%= f.label :data_dg_ckd %>
    <%= f.text_field :data_dg_ckd %>
  </div>
  <div class="field">
    <%= f.label :data_dg_diabet %>
    <%= f.text_field :data_dg_diabet, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.input :centru, :collection => Pacient::CENTRE, :as => :radio, :label => "Selectează centru" %>
  </div>
  <%= link_to 'Printează un inform consent', consent_pacients_path(:format => 'pdf'), :method => :get %>

    <%= f.input :semnat_icf, :label => "Bifează dacă pacientul a semnat inform consentul", :as => :boolean %>
  <div class="actions">
    <%= f.submit 'Adaugă pacient' %>
  </div>
<% end %>
</div>

app/views/pacients/edit.html.erb
<h1>Editing pacient</h1>

<%= render 'form' %>

<%= link_to 'Show', @pacient %> |
<%= link_to 'Back', pacients_path %>

app/views/pacients/includere.html.erb
<%= javascript_include_tag "includere" %>
<%= stylesheet_link_tag "includere" %>
<h2> Formularul de includere pentru <%= @pacient.nume %></h2><br />
<%= simple_form_for @pacient, :remote => true do |f| %>

<h3> Date paraclinice </h3>
<%= f.simple_fields_for :paraclinices, @pacient.paraclinices.build(:tip_vizita => "includere") do |paraclinics| %>
  <%= paraclinics.input :data%>
  <%= paraclinics.input :creatinina %>
  <%= paraclinics.input :uree %>
  <%= paraclinics.input :albumina_urinara_spot %>
  <%= paraclinics.input :creatinina_urinara %>
  <%= paraclinics.input :hco3, :label => "Bicarbonat seric" %>
  <%= paraclinics.input :hba1c, :label => "Hemoglobina glicozilata" %>
<% end %>
<h3> Date anamnestice </h2>
<%= f.simple_fields_for :anamnezas, @pacient.anamnezas.build(:tip_vizita => "includere") do |anamneza| %>
  <%= anamneza.input :neoplasm , :label => "Dacă pacientul e diagnosticat cu neoplasm precizaţi locaţia"%>
<% end %>
<h3> Scor SGA </h3>
<%= f.simple_fields_for :sgas, @pacient.sgas.build(:tip_vizita => "includere") do |sga| %>
  <%= sga.input :modificari_greutate, :collection => [["Fără modificări",0], ["Scădere <5%",1,],["Scădere 5-10%",2],["Scădere 10-15%",3],["Peste 15%",4 ]], :label_method =>:first, :value_method => :last %>
  <%= sga.input :modificari_aport_alimentar, :collection => [["Fără modificări",0], ["Aport suboptimal",1], ["Scădere globală moderată",2], ["Dietă lichidiană",3], ["Înfometare",4]], :label_method => :first, :value_mathod => :last  %>
  <%= sga.input :simptome_gi, :collection => [["Fără simptome",0], ["Greţuri",1], ["Vărsături sau simptome GI moderate",2], ["Diaree/vărsături frecvente",3], ["Anorexie",4]], :label_method => :first, :value_method => :last  %>
  <%= sga.input :capacitate_functionala, :collection => [["Bună",0], ["Dificultăţi la mers",1], ["Dificultăţi de menaj",2], ["Dificultăţi la eforturi minime",3], ["Imobilizare la pat/fotoliu",4]], :label_method => :first, :value_method => :last  %>
  <p> Legată de statusul nutriţional </p>
  <%= sga.input :comorbiditatea, :collection => [["Fără comorbidităţi",0], ["Comorbidităţi usoare/neasociate cu BRC",1], ["Comorbidităţi moderate",2], ["O comorbiditate majora",3], ["mai multe comorbidităţi majore",4]], :label_method => :first, :value_method => :last  %>
  <p> trebuie pusă explicaţia sga la indemână </p>
  <%= sga.input :grasime, :collection => [["Fără modificări",0], ["Minimă",1], ["Moderată",2], ["Severă",3]] , :label_method => :first, :value_method => :last  %>
  <%= sga.input :amiotrofie, :collection => [["Fără modificări",0], ["Minimă",1], ["Moderată",2], ["Severe",3]], :label_method => :first, :value_method => :last %>
  <%= sga.input :imc, :collection => [["peste 24",0], ["20-23,9",1], ["18-19,9",2],["16-17,9",3], ["sub 16",4]], :label_method => :first, :value_method => :last  %>
  <%= sga.input :pcr, :collection => [["sub 1",0],["1-5",1], ["5,1-10",2],["10,1-25",3],["<25",4]], :label_method => :first, :value_method => :last, :hint => "mg/dL"  %>
  <%= sga.input :feritina, :collection => [["200-400",0],["400-600",1], ["600-800",2], ["800-1200",3], [">1200",4]], :label_method => :first, :value_method => :last, :hint =>"în cazul terapiei cu Fe IV pacientul e trecut in clasă inferioară"  %>
  <%= sga.input :albumina, :collection => [[">4",0],["3,5-3,9",1],["3-3,4",2],["2,5-3",3],["<2",4]], :label_method => :first, :value_method => :last , :label => "Albumină serică" %>
<% end %>
<%= f.input :inclus, :label => "Bifează dacă a semnat inform consentu" %>
<p> Poate ar trebui uploadat inform consentu scanat? </p>
<%= f.submit "Adauga" %>
<% end %>

app/views/pacients/includere.pdf.erb
salut

app/views/pacients/index.html.erb
<div id="pagina">
<div class="simple_form">
  <div class="butoane_index">
    <h1> Pacient nou </h1>
<%= button_to 'Printează un inform consent', consent_pacients_path(:format => 'pdf'), :method => :get %><br /> 
<%= button_to 'Screnează un pacient nou', new_pacient_path, :method => :get  %>
</div>
<h1>Pacienti inscrisi</h1>
<div id="cauta" >
   <%= form_tag pacients_path, :method => 'get' do %>
     <p>
     <%= text_field_tag :search, params[:search] %>
     <%= submit_tag "Caută pacient", :name => nil %>
     </p>
   <% end %>
 </div>
<table>
  <tr>
    <th>Nume</th>
    <th>Prenume</th>
    <th>Cnp</th>
    <th>Telefon1</th>
    <th>Telefon2</th>
    <th>Acţiuni</th>
  </tr>

<% @pacients.each do |pacient| %>
  <tr>
    <td><%= pacient.nume %></td>
    <td><%= pacient.prenume %></td>
    <td><%= pacient.cnp %></td>
    <td><%= pacient.telefon1 %></td>
    <td><%= pacient.telefon2 %></td>
    <td><%= link_to 'Modifică', edit_pacient_path(pacient) %><br />
    <%= link_to 'Şterge', pacient, :confirm => 'Sigur vrei să ştergi acest pacient?', :method => :delete %><br />
    <%= link_to 'Adaugă vizită', pacient_path(pacient) %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @pacients %>

<br />
</div>
</div>

app/views/pacients/new.html.erb
<%= render 'form' %>

<%= link_to 'Înapoi', pacients_path %>

app/views/pacients/randomizare.html.erb
<h2> Formularul de randomizare pentru <%= @pacient.nume %></h2><br />
<%= simple_form_for ([@pacient, @anamneza]), :html => {:multipart => true} do |f| %>
  <% f.error_notification %>
  <div class="field">
    <%= f.input :data, :label => "Data examinării" %>
  </div>
  <h3> Date anamnestice </h3>
<div class="field">
    <%= f.label "Fumători: Câte pachete/an" %>
    <%= f.text_field :fumator %>
  </div>
  <div class="field">
    <%= f.label "Consum etanol" %>
    <%= f.number_field :etanol, :label => "Băuturi/zi" %>
  </div>
  <div class="field">
    <%= f.label "Bifează dacă pacientul a suferit infarct miocardic in antecedente" %>
    <%= f.check_box :ima %>
  </div>
  <div class="field">
    <%= f.label "Bifează dacă pacientul suferă de angină pectorală" %>
    <%= f.check_box :angina %>
  </div>
  <div class="field">
    <%= f.input :icc , :collection => ["fară", "NYHA I", "NYHA II", "NYHA III", "NYHA IV"], :label => "Dacă pacientul are insuficienţă cardiacă alegeţi clasa NYHA"%>
  </div>
  <div class="field">
    <%= f.label "Bifaţi dacă pacientul a avut AVC în antecedente" %>
    <%= f.check_box :avc %>
  </div>
  <div class="field">
    <%= f.label "Bifaţi dacă pacientul a fost diagnosticat cu arteriopatie obliterantă" %>
    <%= f.check_box :aomi %>
  </div>
  <div class="field">
    <%= f.label "Bifaţi dacă pacientul a suferit amputaţii" %>
    <%= f.check_box :amputatii %>
  </div>
  <div class="field">
    <%= f.label "Bifaţi dacă pacientul a fost diagnosticat cu BPOC" %>
    <%= f.check_box :bpoc %>
  </div>
  <div class="field">
    <%= f.input :hepatopatii , :collection => ["Fără", "Hepatita virala B", "Hepatita virala C", "Hepatita non-virala"], :label => "Dacă pacientul are suferinţă hepatică vă rog alegeţi forma"%>
  </div>
  <div class="field">
    <%= f.label "Dacă pacientul a fost diagnosticat cu neoplasm precizaţi localizarea" %>
    <%= f.text_field :neoplasm %>
  </div>
  <div class="field">
    <%= f.label "Bifaţi dacă pacientul a fost diagnosticat cu retinopatie" %>
    <%= f.check_box :retinopatie %>
  </div>
<% end %>
<h3> Date clinice </h3>
    <%= simple_form_for ([@pacient, @clinic]),:html=>{:multipart =>true} do |f| %>
      <%= f.input :inaltime, :label => "Înălţimea pacientului in cm" %>
      <%= f.input :greutate, :label => "Greutatea pacientului in kg" %>
      <%= f.input :tas, :label => "Tensiunea arterială sistolică a pacientului" %>
      <%= f.input :tad, :label => "Tensiunea arterială diastolică a pacientului" %>
      <%= f.input :circumferinta_abdomen, :label => "Circumferinţa abdomenului in cm" %>
      <%= f.input :circumferinta_brat, :label => "Circumferinţa braţului in cm " %>
      <%= f.input :pliu_cutantat_brat, :label =>"Pliul cutanat al braţului in cm măsurat cu caliperul" %>
      <%= f.input :forta_de_strangere_mana, :label =>"Forţa de strângere a pumnului" %>
    <% end %>

app/views/pacients/screening.html.erb
<%= javascript_include_tag "includere" %>
<%= stylesheet_link_tag "includere" %>
<h2> Formularul de screening pentru <%= @pacient.nume %></h2>
<h3> cu CNP <div id="cnp" span><%= @pacient.cnp %></span></div> </h3><br />
<%= simple_form_for @pacient, :remote => true do |f| %>

<h3> Date paraclinice </h3>
<div class="inputs">
<%= f.simple_fields_for :paraclinices, @pacient.paraclinices.build(:tip_vizita => "screening"), :remote => true do |paraclinics| %>
  <%= paraclinics.input :data, :label => "Data screeningului" %>
  <%= paraclinics.input :creatinina , :hint => '<div id="egfr" span> Calculează eGFR</span></div>'.html_safe %>
  <%= paraclinics.input :uree %>
  <%= paraclinics.input :albumina_urinara_spot %>
  <%= paraclinics.input :creatinina_urinara %>
  <%= paraclinics.input :hco3, :label => "Bicarbonat seric" %>
  <%= paraclinics.input :hba1c, :label => "Hemoglobină glicozilată" %>
  </div>
<% end %>
<div id ="anamneza"><h3> Date anamnestice </h3></div>
<%= f.simple_fields_for :anamnezas, @pacient.anamnezas.build(:tip_vizita => "screening"), :remote => true do |anamneza| %>
  <%= anamneza.input :neoplasm , :label => "Dacă pacientul e diagnosticat cu neoplasm precizaţi locaţia" %>
<% end %>
<br>
<h3> Scor SGA </h3>
<%= f.simple_fields_for :sgas, @pacient.sgas.build(:tip_vizita => "screening") do |sga| %>
<div id="sga_greutate">
  <%= sga.input :modificari_greutate, :collection => [["Fără modificări",0], ["Scădere <5%",1,],["Scădere 5-10%",2],["Scădere 10-15%",3],["Peste 15%",4 ]], :label_method =>:first, :value_method => :last %>
  </div>
  <%= sga.input :modificari_aport_alimentar, :collection => [["Fără modificări",0], ["Aport suboptimal",1], ["Scădere globală moderată",2], ["Dietă lichidiană",3], ["Înfometare",4]], :label_method => :first, :value_mathod => :last  %><br/>
  <%= sga.input :simptome_gi, :collection => [["Fără simptome",0], ["Greţuri",1], ["Vărsături sau simptome GI moderate",2], ["Diaree/vărsături frecvente",3], ["Anorexie",4]], :label_method => :first, :value_method => :last  %>
  <%= sga.input :capacitate_functionala, :collection => [["Bună",0], ["Dificultăţi la mers",1], ["Dificultăţi de menaj",2], ["Dificultăţi la eforturi minime",3], ["Imobilizare la pat/fotoliu",4]], :label_method => :first, :value_method => :last , :hint => "legată de statusul nutriţional " %>
  
  <%= sga.input :comorbiditatea, :collection => [["Fără comorbidităţi",0], ["Comorbidităţi usoare/neasociate cu BRC",1], ["Comorbidităţi moderate",2], ["O comorbiditate majora",3], ["mai multe comorbidităţi majore",4]], :label_method => :first, :value_method => :last, :hint => '<span div id="comorbiditate_hint"> explicaţie</span></div>'.html_safe %>
  <%= sga.input :grasime, :collection => [["Fără modificări",0], ["Minimă",1], ["Moderată",2], ["Severă",3]] , :label_method => :first, :value_method => :last  %>
  <%= sga.input :amiotrofie, :collection => [["Fără modificări",0], ["Minimă",1], ["Moderată",2], ["Severe",3]], :label_method => :first, :value_method => :last %>
  <%= sga.input :imc, :collection => [["peste 24",0], ["20-23,9",1], ["18-19,9",2],["16-17,9",3], ["sub 16",4]], :label_method => :first, :value_method => :last %>
  <%= sga.input :pcr, :collection => [["sub 1",0],["1-5",1], ["5,1-10",2],["10,1-25",3],["<25",4]], :label_method => :first, :value_method => :last, :hint => "mg/dL"  %>
  <%= sga.input :feritina, :collection => [["200-400",0],["400-600",1], ["600-800",2], ["800-1200",3], [">1200",4]], :label_method => :first, :value_method => :last, :hint =>"în cazul terapiei cu Fe IV pacientul e trecut in clasă inferioară"  %>
  <%= sga.input :albumina, :collection => [[">4",0],["3,5-3,9",1],["3-3,4",2],["2,5-3",3],["<2",4]], :label_method => :first, :value_method => :last , :label => "Albumină serică" %>
<% end %>
<%= f.input :inclus, :label => "Bifează dacă a semnat inform consentu" %>
<p> Poate ar trebui uploadat inform consentu scanat? </p>
<div id="commit">
<%= f.submit "Adauga" %>
</div>
<%= link_to 'Adaugă', '#', :class => 'submit_me' %>
<% end %>

app/views/pacients/show.html.erb
<p id="notice"><%= notice %></p>
<div id="pagina">
  <div class="simple_form">
<h3> Navigare </h3>
<%= link_to 'Schimbă datele pacientului', edit_pacient_path(@pacient) %> |
<%= link_to 'Înapoi la pacienţi', pacients_path %>
<h3> Date Pacient </h3>
<p>
  <b>Nume:</b>
  <%= @pacient.nume %>
  <b>Prenume:</b>
  <%= @pacient.prenume %>
</p>

<p>
  <b>Cnp:</b>
  <%= @pacient.cnp %>
</p>
<h3> Date opţionale </h3>
<p>
  <b>Telefon1:</b>
  <%= @pacient.telefon1 %>
  <b>Telefon2:</b>
  <%= @pacient.telefon2 %>
</p>

<p>
  <b>Adresa:</b>
  <%= @pacient.adresa %>
</p>
<p>
 <b> Centru:</b>
 <%= @pacient.centru %>

<p>
  <b>Data dg ckd:</b>
  <%= @pacient.data_dg_ckd %>
  <b>Data dg diabet:</b>
  <%= @pacient.data_dg_diabet %>
</p>
<h3> Informaţii </h3>
Pacient inclus(d/n), Grup(control/intensiv)
<h3> Tabel cu vizite </h3>
<table>
  <tr>
    <th> Screening </th>
    <th> Randomizare </th>
    <th> Intervenţie </th>
    <th> Mijloc </th>
    <th> PostIntervenţie </th>
    <th> Vizită Neprogramată </th>
    <th> Vizita standard </th>
  </tr>
  <tr>
    <% data_screening = @pacient.vizita.where(:tip => "screening").first.data %>
    <td> <%= link_to data_screening, vizitum_path(@pacient.vizita.where(:tip => "screening").first) %></td>
    <td> <%= link_to data_screening.advance(:months => 1) %>
      Peste <%= data_screening.advance(:months => 1).mjd - Date.today.mjd %> zile </td>

  </tr>
</table>



<h3> Acţiuni </h3>
<%= link_to 'Includere', new_pacient_vizitum_path(@pacient) %>|
<%= link_to 'Ieşit din studiu' %>
</div>
</div>