config/routes.rb
Docbic9::Application.routes.draw do
  

  match 'pacients/verifica_cnp', :controller => "pacients", :action => "verifica_cnp"
  resources :vizita do 
    resource :paraclinice
    resource :mi
    resource :clinic
    resource :anamneza
    resource :sga
  end
  resources :pacients do 
    member do
      get "screening"
      get "verifica_cnp"
    end
    collection do
      get "consent"
    end
    resources :vizita do
      resources :paraclinices
    end
    resources :sf36s
    resources :paraclinices
    resources :medicamentes
    resources :pacient_iesits
  end

   root :to => 'pacients#index'

end

app/models/anamneza.rb
class Anamneza < ActiveRecord::Base
  belongs_to :vizitum
end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
  belongs_to :vizitum
  validates_presence_of :inaltime, :if => :screening?
  validates_presence_of :greutate, :if => :screening?
  def screening?
    self.vizitum.tip == "screening"
  end
end

app/models/medicamente.rb
class Medicamente < ActiveRecord::Base
  belongs_to :vizitum
end

app/models/mi.rb
class Mi < ActiveRecord::Base
  belongs_to :vizitum
end

app/models/pacient.rb
#encoding: utf-8
class Pacient < ActiveRecord::Base
  self.per_page = 5
  CENTRE = ["Paulescu", "Davila"]
  has_many :vizita
  accepts_nested_attributes_for :vizita
  validates :semnat_icf, :acceptance => true #, :message => "E musai ca pacientul să semneze inform consentul"
  validates :cnp, :length => { :is =>13, :wrong_length => "CNP are 13 cifre" }, :numericality => { :only_integer =>true}
  validates_format_of :telefon1, :with => /\d{10}/, :message => "Un număr de telefon în România are 10 cifre"
  validates_format_of :telefon2, :with => /\d{10}/, :message => "Un număr de telefon în România are 10 cifre"
  def self.search(search, page) #tot nu merge
    if search
      paginate :per_page => 5, :page => page,
        :conditions => ['nume like ?', "%#{search}%"], :order => 'nume'
      #find(:all, :conditions => ['nume LIKE ?', "%#{search}"])
    else
      find(:all)
    end
  end
end

app/models/pacient_iesit.rb
class PacientIesit < ActiveRecord::Base
  belongs_to :pacient
end

app/models/paraclinice.rb
class Paraclinice < ActiveRecord::Base
  belongs_to :vizita
  validates_presence_of :hba1c, :if => :screening?
  validates_presence_of :hco3, :if => :screening?
  def screening?
    self.vizitum.tip == "screening"
  end
end

app/models/sf36.rb
class Sf36 < ActiveRecord::Base
  belongs_to :pacient
end

app/models/sga.rb
class Sga < ActiveRecord::Base
end

app/models/vizitum.rb
class Vizitum < ActiveRecord::Base
  #nu imi trebuie validari pt screening 
  belongs_to :pacient
  has_one :paraclinice
  has_one :medicamente
  has_one :mi
  has_one :anamneza
  has_one :clinic
  has_one :sga
  accepts_nested_attributes_for :paraclinice
  accepts_nested_attributes_for :medicamente
  accepts_nested_attributes_for :mi
  accepts_nested_attributes_for :sga
  accepts_nested_attributes_for :clinic
  accepts_nested_attributes_for :anamneza
  before_update :prelucreaza_nutritia
  #validates_presence_of :data, :if => :screening?
  def screening?
    self.tip == "screening"
  end
  def criterii_includere
    if self.tip == "screening"
      if self.paraclinice.hba1c > 8
        errors.add_to_base("Pacient dezechilibrat")
      end
    end
  end
  private
  def verifica_criterii
    if self.tip == "screening" #conditiile nu sunt bune
      puts 'glicozilata e'
      puts self.paraclinice.hba1c
      #if self.paraclinice.hba1c > 8 or calculeaza_epi > 30 or self.paraclinice.hco3 < 20
        #self.pacient.inclus=false
      #end
    end
  end
  def calculeaza_epi
    cnp = self.pacient.cnp
    an_nastere = '19'+ cnp[1,2]
    varsta = Date.today.year.to_int - an_nastere
    if cnp[0] == 1
      k = 0.9
      alfa = -0.4111
      coeficient = 1
    elsif cnp[0] == 2
      k = 0.7
      alfa = -0.329
      coeficient = 1.018
    end
    raport = self.paraclinice.creatinina/k
    primu = [raport, 1].min**-0.411
    doilea = [raport, 1].max ** -1.209
    treilea = 0.993**89
    puts 'epi zice'
    puts 141*primu*doilea*treilea*coeficient
    141*primu*doilea*treilea*coeficient
  end
  def calculeaza_bmi_categorie(inaltime, greutate)
    puts 'G=', greutate, 'I=', inaltime
    bmi = greutate/(inaltime **2)
    case bmi
    when bmi > 20
      bmi_categorie = 0
    when 18 .. 20
      bmi_categorie = 1
    when 16 .. 18
      bmi_categorie =2
    when bmi <16
      bmi_categorie =3
    end
    puts bmi_categorie
    bmi_categorie
  end
  def prelucreaza_nutritia
    puts 'salut din callback'
    if self.tip == "screening"
      puts 'data vizitei e', self.data
      puts 'data anamnezei e', self.anamneza.data
      puts 'glicozilata e', self.paraclinice.hba1c #merge si pot calcula lucruri
    end
  end
end

class PrelucreazaNutritia
  def before_save(record)
    record.tip = "screening"
  end
  #alias_method :before_save
end

app/controllers/mis_controller.rb
class MisController < InheritedResources::Base
  belongs_to :vizita
end

app/controllers/pacient_iesits_controller.rb
class PacientIesitsController < InheritedResources::Base
end

app/controllers/sgas_controller.rb
class SgasController < InheritedResources::Base
end

app/helpers/anamnezas_helper.rb
module AnamnezasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/helpers/medicamentes_helper.rb
module MedicamentesHelper
end

app/helpers/mis_helper.rb
module MisHelper
end

app/helpers/pacient_iesits_helper.rb
module PacientIesitsHelper
end

app/helpers/pacients_helper.rb
module PacientsHelper
end

app/helpers/sf36s_helper.rb
module Sf36sHelper
end

app/helpers/sgas_helper.rb
module SgasHelper
end

app/helpers/vizita_helper.rb
module VizitaHelper
end

app/views/pacient_iesits/_form.html.erb
<%= form_for(@pacient_iesit) do |f| %>
  <% if @pacient_iesit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pacient_iesit.errors.count, "error") %> prohibited this pacient_iesit from being saved:</h2>

      <ul>
      <% @pacient_iesit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br />
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :motiv %><br />
    <%= f.text_field :motiv %>
  </div>
  <div class="field">
    <%= f.label :pacient %><br />
    <%= f.text_field :pacient %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pacient_iesits/edit.html.erb
<h1>Editing pacient_iesit</h1>

<%= render 'form' %>

<%= link_to 'Show', @pacient_iesit %> |
<%= link_to 'Back', pacient_iesits_path %>

app/views/pacient_iesits/index.html.erb
<h1>Listing pacient_iesits</h1>

<table>
  <tr>
    <th>Data</th>
    <th>Motiv</th>
    <th>Pacient</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pacient_iesits.each do |pacient_iesit| %>
  <tr>
    <td><%= pacient_iesit.data %></td>
    <td><%= pacient_iesit.motiv %></td>
    <td><%= pacient_iesit.pacient %></td>
    <td><%= link_to 'Show', pacient_iesit %></td>
    <td><%= link_to 'Edit', edit_pacient_iesit_path(pacient_iesit) %></td>
    <td><%= link_to 'Destroy', pacient_iesit, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pacient iesit', new_pacient_iesit_path %>

app/views/pacient_iesits/new.html.erb
<h1>New pacient_iesit</h1>

<%= render 'form' %>

<%= link_to 'Back', pacient_iesits_path %>

app/views/pacient_iesits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Data:</b>
  <%= @pacient_iesit.data %>
</p>

<p>
  <b>Motiv:</b>
  <%= @pacient_iesit.motiv %>
</p>

<p>
  <b>Pacient:</b>
  <%= @pacient_iesit.pacient %>
</p>


<%= link_to 'Edit', edit_pacient_iesit_path(@pacient_iesit) %> |
<%= link_to 'Back', pacient_iesits_path %>