config/routes.rb
Docbic9::Application.routes.draw do
  

  match 'pacients/verifica_cnp', :controller => "pacients", :action => "verifica_cnp"
  resources :vizita do 
    resource :paraclinice
    resource :mi
    resource :clinic
    resource :anamneza
    resource :sga
  end
  resources :pacients do 
    member do
      get "screening"
      get "verifica_cnp"
    end
    collection do
      get "consent"
    end
    resources :vizita do
      resources :paraclinices
    end
    resources :sf36s
    resources :paraclinices
    resources :medicamentes
    resources :pacient_iesits
  end

   root :to => 'pacients#index'

end

app/models/anamneza.rb
class Anamneza < ActiveRecord::Base
  belongs_to :vizitum
end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
  belongs_to :vizitum
  validates_presence_of :inaltime, :if => :screening?
  validates_presence_of :greutate, :if => :screening?
  def screening?
    self.vizitum.tip == "screening"
  end
end

app/models/medicamente.rb
class Medicamente < ActiveRecord::Base
  belongs_to :vizitum
end

app/models/mi.rb
class Mi < ActiveRecord::Base
  belongs_to :vizitum
end

app/models/pacient.rb
#encoding: utf-8
class Pacient < ActiveRecord::Base
  self.per_page = 5
  CENTRE = ["Paulescu", "Davila"]
  has_many :vizita
  accepts_nested_attributes_for :vizita
  validates :semnat_icf, :acceptance => true #, :message => "E musai ca pacientul să semneze inform consentul"
  validates :cnp, :length => { :is =>13, :wrong_length => "CNP are 13 cifre" }, :numericality => { :only_integer =>true}
  validates_format_of :telefon1, :with => /\d{10}/, :message => "Un număr de telefon în România are 10 cifre"
  validates_format_of :telefon2, :with => /\d{10}/, :message => "Un număr de telefon în România are 10 cifre"
  def self.search(search, page) #tot nu merge
    if search
      paginate :per_page => 5, :page => page,
        :conditions => ['nume like ?', "%#{search}%"], :order => 'nume'
      #find(:all, :conditions => ['nume LIKE ?', "%#{search}"])
    else
      find(:all)
    end
  end
end

app/models/pacient_iesit.rb
class PacientIesit < ActiveRecord::Base
  belongs_to :pacient
end

app/models/paraclinice.rb
class Paraclinice < ActiveRecord::Base
  belongs_to :vizita
  validates_presence_of :hba1c, :if => :screening?
  validates_presence_of :hco3, :if => :screening?
  def screening?
    self.vizitum.tip == "screening"
  end
end

app/models/sf36.rb
class Sf36 < ActiveRecord::Base
  belongs_to :pacient
end

app/models/sga.rb
class Sga < ActiveRecord::Base
end

app/models/vizitum.rb
class Vizitum < ActiveRecord::Base
  #nu imi trebuie validari pt screening 
  belongs_to :pacient
  has_one :paraclinice
  has_one :medicamente
  has_one :mi
  has_one :anamneza
  has_one :clinic
  has_one :sga
  accepts_nested_attributes_for :paraclinice
  accepts_nested_attributes_for :medicamente
  accepts_nested_attributes_for :mi
  accepts_nested_attributes_for :sga
  accepts_nested_attributes_for :clinic
  accepts_nested_attributes_for :anamneza
  before_update :prelucreaza_nutritia
  #validates_presence_of :data, :if => :screening?
  def screening?
    self.tip == "screening"
  end
  def criterii_includere
    if self.tip == "screening"
      if self.paraclinice.hba1c > 8
        errors.add_to_base("Pacient dezechilibrat")
      end
    end
  end
  private
  def verifica_criterii
    if self.tip == "screening" #conditiile nu sunt bune
      puts 'glicozilata e'
      puts self.paraclinice.hba1c
      #if self.paraclinice.hba1c > 8 or calculeaza_epi > 30 or self.paraclinice.hco3 < 20
        #self.pacient.inclus=false
      #end
    end
  end
  def calculeaza_epi
    cnp = self.pacient.cnp
    an_nastere = '19'+ cnp[1,2]
    varsta = Date.today.year.to_int - an_nastere
    if cnp[0] == 1
      k = 0.9
      alfa = -0.4111
      coeficient = 1
    elsif cnp[0] == 2
      k = 0.7
      alfa = -0.329
      coeficient = 1.018
    end
    raport = self.paraclinice.creatinina/k
    primu = [raport, 1].min**-0.411
    doilea = [raport, 1].max ** -1.209
    treilea = 0.993**89
    puts 'epi zice'
    puts 141*primu*doilea*treilea*coeficient
    141*primu*doilea*treilea*coeficient
  end
  def calculeaza_bmi_categorie(inaltime, greutate)
    puts 'G=', greutate, 'I=', inaltime
    bmi = greutate/(inaltime **2)
    case bmi
    when bmi > 20
      bmi_categorie = 0
    when 18 .. 20
      bmi_categorie = 1
    when 16 .. 18
      bmi_categorie =2
    when bmi <16
      bmi_categorie =3
    end
    puts bmi_categorie
    bmi_categorie
  end
  def prelucreaza_nutritia
    puts 'salut din callback'
    if self.tip == "screening"
      puts 'data vizitei e', self.data
      puts 'data anamnezei e', self.anamneza.data
      puts 'glicozilata e', self.paraclinice.hba1c #merge si pot calcula lucruri
    end
  end
end

class PrelucreazaNutritia
  def before_save(record)
    record.tip = "screening"
  end
  #alias_method :before_save
end

app/controllers/mis_controller.rb
class MisController < InheritedResources::Base
  belongs_to :vizita
end

app/controllers/paraclinices_controller.rb
class ParaclinicesController < InheritedResources::Base
  belongs_to :vizita
end

app/controllers/sgas_controller.rb
class SgasController < InheritedResources::Base
end

app/helpers/anamnezas_helper.rb
module AnamnezasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/helpers/medicamentes_helper.rb
module MedicamentesHelper
end

app/helpers/mis_helper.rb
module MisHelper
end

app/helpers/pacients_helper.rb
module PacientsHelper
end

app/helpers/paraclinices_helper.rb
module ParaclinicesHelper
end

app/helpers/sf36s_helper.rb
module Sf36sHelper
end

app/helpers/sgas_helper.rb
module SgasHelper
end

app/helpers/vizita_helper.rb
module VizitaHelper
end

app/views/paraclinices/_form.html.erb
<%= form_for(@paraclinice) do |f| %>
  <% if @paraclinice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paraclinice.errors.count, "error") %> prohibited this paraclinice from being saved:</h2>

      <ul>
      <% @paraclinice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hemoglobina %><br />
    <%= f.text_field :hemoglobina %>
  </div>
  <div class="field">
    <%= f.label :hematocrit %><br />
    <%= f.text_field :hematocrit %>
  </div>
  <div class="field">
    <%= f.label :pcr %><br />
    <%= f.text_field :pcr %>
  </div>
  <div class="field">
    <%= f.label :glicemie %><br />
    <%= f.text_field :glicemie %>
  </div>
  <div class="field">
    <%= f.label :hba1c %><br />
    <%= f.text_field :hba1c %>
  </div>
  <div class="field">
    <%= f.label :colesterol_total %><br />
    <%= f.text_field :colesterol_total %>
  </div>
  <div class="field">
    <%= f.label :hdl_colesterol %><br />
    <%= f.text_field :hdl_colesterol %>
  </div>
  <div class="field">
    <%= f.label :trigliceride %><br />
    <%= f.text_field :trigliceride %>
  </div>
  <div class="field">
    <%= f.label :albumina %><br />
    <%= f.text_field :albumina %>
  </div>
  <div class="field">
    <%= f.label :tsat %><br />
    <%= f.text_field :tsat %>
  </div>
  <div class="field">
    <%= f.label :feritina %><br />
    <%= f.text_field :feritina %>
  </div>
  <div class="field">
    <%= f.label :calcemie %><br />
    <%= f.text_field :calcemie %>
  </div>
  <div class="field">
    <%= f.label :fosfatemie %><br />
    <%= f.text_field :fosfatemie %>
  </div>
  <div class="field">
    <%= f.label :fosfataza_alcalina %><br />
    <%= f.text_field :fosfataza_alcalina %>
  </div>
  <div class="field">
    <%= f.label :pth %><br />
    <%= f.text_field :pth %>
  </div>
  <div class="field">
    <%= f.label :ph %><br />
    <%= f.text_field :ph %>
  </div>
  <div class="field">
    <%= f.label :pco2 %><br />
    <%= f.text_field :pco2 %>
  </div>
  <div class="field">
    <%= f.label :hco3 %><br />
    <%= f.text_field :hco3 %>
  </div>
  <div class="field">
    <%= f.label :sodiu %><br />
    <%= f.text_field :sodiu %>
  </div>
  <div class="field">
    <%= f.label :potasiu %><br />
    <%= f.text_field :potasiu %>
  </div>
  <div class="field">
    <%= f.label :clor %><br />
    <%= f.text_field :clor %>
  </div>
  <div class="field">
    <%= f.label :creatinina %><br />
    <%= f.text_field :creatinina %>
  </div>
  <div class="field">
    <%= f.label :uree %><br />
    <%= f.text_field :uree %>
  </div>
  <div class="field">
    <%= f.label :uree_urinara %><br />
    <%= f.text_field :uree_urinara %>
  </div>
  <div class="field">
    <%= f.label :albumina_urinara_spot %><br />
    <%= f.text_field :albumina_urinara_spot %>
  </div>
  <div class="field">
    <%= f.label :creatinina_urinara %><br />
    <%= f.text_field :creatinina_urinara %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :pacient %><br />
    <%= f.text_field :pacient %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paraclinices/edit.html.erb
<h1>Editing paraclinice</h1>

<%= render 'form' %>

<%= link_to 'Show', @paraclinice %> |
<%= link_to 'Back', paraclinices_path %>

app/views/paraclinices/index.html.erb
<h1>Listing paraclinices</h1>

<table>
  <tr>
    <th>Hemoglobina</th>
    <th>Hematocrit</th>
    <th>Pcr</th>
    <th>Glicemie</th>
    <th>Hba1c</th>
    <th>Colesterol total</th>
    <th>Hdl colesterol</th>
    <th>Trigliceride</th>
    <th>Albumina</th>
    <th>Tsat</th>
    <th>Feritina</th>
    <th>Calcemie</th>
    <th>Fosfatemie</th>
    <th>Fosfataza alcalina</th>
    <th>Pth</th>
    <th>Ph</th>
    <th>Pco2</th>
    <th>Hco3</th>
    <th>Sodiu</th>
    <th>Potasiu</th>
    <th>Clor</th>
    <th>Creatinina</th>
    <th>Uree</th>
    <th>Uree urinara</th>
    <th>Albumina urinara spot</th>
    <th>Creatinina urinara</th>
    <th>Data</th>
    <th>Pacient</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @paraclinices.each do |paraclinice| %>
  <tr>
    <td><%= paraclinice.hemoglobina %></td>
    <td><%= paraclinice.hematocrit %></td>
    <td><%= paraclinice.pcr %></td>
    <td><%= paraclinice.glicemie %></td>
    <td><%= paraclinice.hba1c %></td>
    <td><%= paraclinice.colesterol_total %></td>
    <td><%= paraclinice.hdl_colesterol %></td>
    <td><%= paraclinice.trigliceride %></td>
    <td><%= paraclinice.albumina %></td>
    <td><%= paraclinice.tsat %></td>
    <td><%= paraclinice.feritina %></td>
    <td><%= paraclinice.calcemie %></td>
    <td><%= paraclinice.fosfatemie %></td>
    <td><%= paraclinice.fosfataza_alcalina %></td>
    <td><%= paraclinice.pth %></td>
    <td><%= paraclinice.ph %></td>
    <td><%= paraclinice.pco2 %></td>
    <td><%= paraclinice.hco3 %></td>
    <td><%= paraclinice.sodiu %></td>
    <td><%= paraclinice.potasiu %></td>
    <td><%= paraclinice.clor %></td>
    <td><%= paraclinice.creatinina %></td>
    <td><%= paraclinice.uree %></td>
    <td><%= paraclinice.uree_urinara %></td>
    <td><%= paraclinice.albumina_urinara_spot %></td>
    <td><%= paraclinice.creatinina_urinara %></td>
    <td><%= paraclinice.data %></td>
    <td><%= paraclinice.pacient %></td>
    <td><%= link_to 'Show', paraclinice %></td>
    <td><%= link_to 'Edit', edit_paraclinice_path(paraclinice) %></td>
    <td><%= link_to 'Destroy', paraclinice, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Paraclinice', new_paraclinice_path %>

app/views/paraclinices/new.html.erb
<h1>New paraclinice</h1>

<%= render 'form' %>

<%= link_to 'Back', paraclinices_path %>

app/views/paraclinices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Hemoglobina:</b>
  <%= @paraclinice.hemoglobina %>
</p>

<p>
  <b>Hematocrit:</b>
  <%= @paraclinice.hematocrit %>
</p>

<p>
  <b>Pcr:</b>
  <%= @paraclinice.pcr %>
</p>

<p>
  <b>Glicemie:</b>
  <%= @paraclinice.glicemie %>
</p>

<p>
  <b>Hba1c:</b>
  <%= @paraclinice.hba1c %>
</p>

<p>
  <b>Colesterol total:</b>
  <%= @paraclinice.colesterol_total %>
</p>

<p>
  <b>Hdl colesterol:</b>
  <%= @paraclinice.hdl_colesterol %>
</p>

<p>
  <b>Trigliceride:</b>
  <%= @paraclinice.trigliceride %>
</p>

<p>
  <b>Albumina:</b>
  <%= @paraclinice.albumina %>
</p>

<p>
  <b>Tsat:</b>
  <%= @paraclinice.tsat %>
</p>

<p>
  <b>Feritina:</b>
  <%= @paraclinice.feritina %>
</p>

<p>
  <b>Calcemie:</b>
  <%= @paraclinice.calcemie %>
</p>

<p>
  <b>Fosfatemie:</b>
  <%= @paraclinice.fosfatemie %>
</p>

<p>
  <b>Fosfataza alcalina:</b>
  <%= @paraclinice.fosfataza_alcalina %>
</p>

<p>
  <b>Pth:</b>
  <%= @paraclinice.pth %>
</p>

<p>
  <b>Ph:</b>
  <%= @paraclinice.ph %>
</p>

<p>
  <b>Pco2:</b>
  <%= @paraclinice.pco2 %>
</p>

<p>
  <b>Hco3:</b>
  <%= @paraclinice.hco3 %>
</p>

<p>
  <b>Sodiu:</b>
  <%= @paraclinice.sodiu %>
</p>

<p>
  <b>Potasiu:</b>
  <%= @paraclinice.potasiu %>
</p>

<p>
  <b>Clor:</b>
  <%= @paraclinice.clor %>
</p>

<p>
  <b>Creatinina:</b>
  <%= @paraclinice.creatinina %>
</p>

<p>
  <b>Uree:</b>
  <%= @paraclinice.uree %>
</p>

<p>
  <b>Uree urinara:</b>
  <%= @paraclinice.uree_urinara %>
</p>

<p>
  <b>Albumina urinara spot:</b>
  <%= @paraclinice.albumina_urinara_spot %>
</p>

<p>
  <b>Creatinina urinara:</b>
  <%= @paraclinice.creatinina_urinara %>
</p>

<p>
  <b>Data:</b>
  <%= @paraclinice.data %>
</p>

<p>
  <b>Pacient:</b>
  <%= @paraclinice.pacient %>
</p>


<%= link_to 'Edit', edit_paraclinice_path(@paraclinice) %> |
<%= link_to 'Back', paraclinices_path %>